language: swift
osx_image: xcode10.1

env:
  global:
    - LANG=en_US.UTF-8
    - LC_ALL=en_US.UTF-8
    - WORKSPACE="LocalizableUIElements/LocalizableUIElements.xcodeproj"
    - IOS_FRAMEWORK_SCHEME="LocalizableUIElements/LocalizableUIElements"
    - IOS_SDK=iphonesimulator12.1
  matrix:
    - DESTINATION="platform=iOS Simulator,OS=12.1,name=iPhone 6" TARGET="LocalizableUIElements" SDK="$IOS_SDK" RUN_TESTS="build"
    - DESTINATION="platform=iOS Simulator,OS=12.1,name=iPhone 6" TARGET="LocalizableUIElementsDemo" SDK="$IOS_SDK" RUN_TESTS="build"
    - DESTINATION="platform=iOS Simulator,OS=12.1,name=iPhone 6" TARGET="LocalizableUIElementsTests" SDK="$IOS_SDK" RUN_TESTS="test"
before_install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-darwin-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild -list -project "$WORKSPACE"
  - travis_retry xcodebuild -project "$WORKSPACE" -scheme "$TARGET" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO $RUN_TESTS | xcpretty -c;
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email: true
